version: '3'

services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'

    environment:
      POSTGRES_PASSWORD: replaceme

    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
