import 'tags.dart';

class Article {
  late final String title;
  late final String link;
  late final int time;
  late final List<Tags> tags;

  Article({required this.title, required this.link, required this.time, required this.tags});

  Article.fromJson(Map<String, dynamic> object) {
    this.title = object['title'];
    // print(this.title);
    this.link = object['link'];
    // print(this.link);
    this.time = object['time'];
    // print(this.time);
    // print(object['tags'].runtimeType);
    this.tags = TagsfromJson(object['tags']);
    // print(this.tags);
  }

  Map<String, dynamic> toJson() => {
    "title": this.title,
    "link": this.link,
    "time": this.time,
    "tags": TagstoJson(this.tags),
  };
}

List<Article> demoArts = [
Article(title:"Getting Your Baby to Sleep Through the Night: Tips for New Moms", link:"https://baby.lovetoknow.com/baby-sleep-advice/when-do-babies-start-sleeping-through-night-parents-guide",	time: 5, tags: [Tags.Sleep,
Tags.Tips,
Tags.Advice]),
Article(title:"Here's When Your Baby Can Safely Sleep on Their Stomach", link:"https://baby.lovetoknow.com/heres-when-your-baby-can-safely-sleep-their-stomach",	time: 2, tags: [Tags.Sleep,
Tags.Health,
]),
Article(title:"How Long Should Your Baby Sleep in Your Room?", link:"https://baby.lovetoknow.com/baby-sleep-advice/how-long-should-your-baby-sleep-your-room",	time: 3, tags: [Tags.Sleep,
Tags.Advice]),
Article(title:"6 Tips to Help Your Baby Fall Asleep Without Being Held", link:"https://baby.lovetoknow.com/baby-sleep-advice/how-get-baby-sleep-without-being-held",	time: 3, tags: [Tags.Sleep,
Tags.Tips,
Tags.Advice]),
Article(title:"Sweet Baby Lullabies to Coax Your Little One to Sleep", link:"https://baby.lovetoknow.com/baby-sleep-advice/sweet-baby-lullabies",	time: 5, tags: [Tags.Sleep,
Tags.Tips,
Tags.Advice]),
Article(title:"My experiences after I returned home with a child prompted me to start a support group for single parents! - Laila Zafar", link:"https://www.parentcircle.com/desi-single-parents-support-chat-groups-by-laila-zafar-founder-of-the-village/article",	time: 5, tags: [Tags.Inspiring,
Tags.Experiences]),
Article(title:"How I Break Stereotypes Every Day While Raising My Child: A Heartfelt Account By A Mom", link:"https://www.parentcircle.com/parenting-story-of-dipanwita-sarkar-on-how-to-break-stereotypes-every-day-while-raising-a-child/article",	time: 8, tags: [Tags.Inspiring,
Tags.Experiences]),
Article(title:"“My Journey As A Parent To A Special Child Was Going Fine Till An Incident Shook My Soul”", link:"https://www.parentcircle.com/parenting-story-of-sumita-ghosh-a-working-parent-of-special-child/article",	time: 2, tags: [Tags.Inspiring,
Tags.Experiences]),
Article(title:"9 ways a single parent can a maintain a healthy balance between parenting and work", link:"https://timesofindia.indiatimes.com/life-style/parenting/moments/9-ways-a-single-parent-can-a-maintain-a-healthy-balance-between-parenting-and-work/articleshow/83663265.cms",	time: 3, tags: [Tags.Advice,
Tags.WorkLifeBalance,
Tags.Career]),
Article(title:"Here are six lessons about being a single mom I’d like to share", link:"https://www.mother.ly/parenting/single-parenting/single-motherhood-postpartum-perspective/",	time: 5, tags: [Tags.Advice,
Tags.Experiences]),
Article(title:"Importance Of Having Health Insurance For Single Moms", link:"https://www.momspresso.com/parenting/article/importance-of-having-health-insurance-for-single-moms-vwbytjd2i49m",	time: 2, tags: [Tags.Advice,
Tags.Health,
Tags.Finance]),
Article(title:"Where to Find Financial Help as a Single Mom (US)", link:"https://www.whattoexpect.com/family/financial-help-for-single-moms/",	time: 6, tags: [Tags.Advice,
Tags.Finance]),
Article(title:"Advice for single parents - NHS England", link:"https://www.nhs.uk/conditions/baby/support-and-services/advice-for-single-parents/",	time: 3, tags: [Tags.Advice,
Tags.Finance]),
Article(title:"Your post-pregnancy body", link:"https://www.nhs.uk/conditions/baby/support-and-services/your-post-pregnancy-body/",	time: 3, tags: [Tags.Health,
]),
Article(title:"Keeping fit and healthy with a baby", link:"https://www.nhs.uk/conditions/baby/support-and-services/keeping-fit-and-healthy-with-a-baby/",	time: 4, tags: [Tags.Health,
Tags.Excerise,
Tags.Advice]),
Article(title:"Coping with stress after having a baby", link:"https://www.nhs.uk/conditions/baby/support-and-services/coping-with-stress-after-having-a-baby/",	time: 2, tags: [Tags.Health,
Tags.MentalHealth,
Tags.Advice,
Tags.SelfCare]),
Article(title:"Look after your emotional wellbeing", link:"https://www.tommys.org/pregnancy-information/after-birth/single-parenting",	time: 5, tags: [Tags.MentalHealth,
Tags.Advice,
Tags.SelfCare]),
Article(title:"7 Self-Care Tips for Single Moms", link:"https://amyandrose.com/blogs/parenting/self-care-tips-for-single-moms/",	time: 3, tags: [Tags.MentalHealth,
Tags.Advice,
Tags.SelfCare]),
Article(title:"20 single mom survival tips from other single moms", link:"https://www.care.com/c/where-to-find-help-for-single-mothers/	",time: 15, tags: [Tags.MentalHealth,
Tags.Advice,
Tags.SelfCare,
Tags.Finance,
Tags.Career]),
Article(title:"Self-Care for Single Moms & Dads", link:"https://www.verywellfamily.com/self-care-for-single-moms-and-dads-4121243",	time: 8, tags: [Tags.MentalHealth,
Tags.Advice,
Tags.SelfCare]),
Article(title:"Single supermoms, we're here to help you plan your finances", link:"https://tweakindia.com/work/money/9-financial-problems-faced-by-single-moms-and-how-to-solve-them/#:~:text=Kapoor started a Sukanya Samriddhi,child is 21 years old.	",time: 20, tags: [Tags.Finance,
Tags.Career,
Tags.Advice]),
Article(title:"What are the government initiative to help a single mom plan for her girl child’s future in India", link:"https://savvywomen.tomorrowmakers.com/kids/what-are-government-initiatives-help-single-mom-plan-her-girl-childs-future-india-article",	time: 5, tags: [Tags.Finance,
Tags.Health]),
Article(title:"Financial tips for single mothers", link:"https://economictimes.indiatimes.com/wealth/plan/financial-tips-for-single-mothers/articleshow/48212095.cms?from=mdr	",time: 10, tags: [Tags.Finance,
Tags.Advice,
Tags.Experiences,
Tags.Inspiring]),
Article(title:"Right To Privacy Of Single Mothers", link:"https://www.legalserviceindia.com/legal/article-6728-right-to-privacy-of-single-mothers.html#:~:text=The Hon'ble Supreme Court of India in a landmark,legal guardian of her child.",	time: 5, tags: [Tags.LegalAdvice]),
Article(title:"PMMVY: Pradhan Mantri Matru Vandana Yojana - Eligibility, Features and Registration Process", link:"https://www.acko.com/health-insurance/pradhan-mantri-matru-vandana-yojana/	",time: 20, tags: [Tags.Finance,
Tags.Health,
Tags.Advice]),
Article(title:"Telangana pension for single women: Plan will not work if disbursal remains difficult", link:"https://www.hindustantimes.com/opinion/telangana-pension-for-single-women-plan-will-not-work-if-disbursal-remains-difficult/story-WrOkhhEqGGpxlCobqn3GsO.html",	time: 3, tags: [Tags.Finance]),
Article(title:"Mahila Samman Patra – Meaning, Features, Eligibility, Benefits", link:"https://www.fisdom.com/mahila-samman-patra-features-eligibility-benefits/",	time: 5, tags: [Tags.Finance,
Tags.Health]),
Article(title:"15 Career Tips For Single Moms, From Successful Single Mom Professionals", link:"https://fairygodboss.com/career-topics/single-mom	",time: 10, tags: [Tags.Career,
Tags.SelfCare,
Tags.Finance,
Tags.WorkLifeBalance,
Tags.Advice]),
Article(title:"Survival Strategies for Single Working Parents", link:"https://www.monster.com/career-advice/article/single-working-parents",	time: 5, tags: [Tags.Career,
Tags.SelfCare,
Tags.Finance,
Tags.WorkLifeBalance,
Tags.Advice]),
Article(title:"Career Advice for Single Parents", link:"https://www.fool.com/careers/2017/07/16/career-advice-for-single-parents.aspx",	time: 3, tags: [Tags.Career,
Tags.SelfCare,
Tags.Finance,
Tags.WorkLifeBalance,
Tags.Advice]),
Article(title:"A Single Mom’s Guide to Career Advancement", link:"https://theglasshammer.com/2015/04/a-single-moms-guide-to-career-advancement-for-working-moms-too/",	time: 3, tags: [Tags.Career,
Tags.SelfCare,
Tags.Finance,
Tags.WorkLifeBalance,
Tags.Advice]),
Article(title:"Changing Careers or Retraining as a Single Parent", link:"https://www.refreshingacareer.com/refresh-your-career/parenthood/single-parents/",	time: 5, tags: [Tags.Career,
Tags.SelfCare,
Tags.Finance,
Tags.WorkLifeBalance,
Tags.Advice]),
Article(title:"8 Mental Health Challenges Single Moms Face", link:"https://www.talkspace.com/blog/8-mental-health-challenges-single-moms-face/#:~:text=Unfortunately many single moms don,depression%2C anxiety disorders and PTSD.",	time: 5, tags: [Tags.SelfCare,
Tags.MentalHealth,
Tags.Health]),
Article(title:"Maintaining Your Mental Health as a Single Parent", link:"https://mytransformations.com/post/maintaining-your-mental-health-as-a-single-parent",	time: 3, tags: [Tags.SelfCare,
Tags.MentalHealth,
Tags.Health]),
Article(title:"10 Powerful Mental Health Tips for Single Moms", link:"https://www.kodakcares.org/post/10-powerful-mental-health-tips-single-moms",	time: 5, tags: [Tags.SelfCare,
Tags.MentalHealth,
Tags.Health]),
Article(title:"Mental Health Tips for Single Parents", link:"https://centerstone.org/our-resources/health-wellness/mental-health-tips-for-single-parents/",	time: 2, tags: [Tags.SelfCare,
Tags.MentalHealth,
Tags.Health]),
Article(title:"Wellbeing Tips for Single Parents", link:"https://blog.plummhealth.com/mental-health/counselling/wellbeing-tips-for-single-parents/",	time: 5, tags: [Tags.SelfCare,
Tags.MentalHealth,
Tags.Health]),
Article(title:"15 Ways to Help Your Baby Love Food as Much as You Do", link:"https://www.parents.com/recipes/tips/ways-to-make-your-baby-love-food-as-much-as-you-do/",	time: 8, tags: [Tags.Health,
Tags.Food,
Tags.Advice,
Tags.Tips]),
Article(title:"Kids and Food: 10 Tips for Parents", link:"https://kidshealth.org/en/parents/eating-tips.html",	time: 2, tags: [Tags.Health,
Tags.Food,
Tags.Advice,
Tags.Tips]),
Article(title:"Healthy Eating Plan for a Single Mom on a Budget", link:"https://healthyeating.sfgate.com/healthy-eating-plan-single-mom-budget-11507.html",	time: 2, tags: [Tags.Health,
Tags.Food,
Tags.Advice,
Tags.Tips]),
Article(title:"Feeding your baby: 1–2 years - UNICEF", link:"https://www.unicef.org/parenting/food-nutrition/feeding-your-baby-1-2-years",	time: 3, tags: [Tags.Health,
Tags.Food,
Tags.Advice,
Tags.Tips]),
Article(title:"Easy and Effective Exercises for Babies", link:"https://parenting.firstcry.com/articles/easy-and-effective-exercises-for-babies/#:~:text=Place baby on his back,as if pedalling a bicycle.&text=This is a great exercise,%2C arm%2C and hand muscles.",	time: 5, tags: [Tags.Health,
Tags.Excerise,
Tags.Advice,
Tags.Tips]),
Article(title:"9 Easy Exercises For Babies At Different Ages", link:"momjunction.com/articles/easy-exercises-for-newborn-babies-ages_00761066/	",time: 12, tags: [Tags.Health,
Tags.Excerise,
Tags.Advice,
Tags.Tips]),
Article(title:"14 Baby Exercises to Get Your Baby Moving", link:"https://www.thebump.com/a/baby-exercises	",time: 15, tags: [Tags.Health,
Tags.Excerise,
Tags.Advice,
Tags.Tips]),
Article(title:"9 of the best baby formulas", link:"https://www.medicalnewstoday.com/articles/best-formula-for-babies	",time: 15, tags: [Tags.Health,
Tags.Food,
Tags.Advice,
Tags.Tips]),
Article(title:"The 10 Best Baby Formulas", link:"https://www.healthline.com/health/baby/best-baby-formula	",time: 15, tags: [Tags.Health,
Tags.Food,
Tags.Advice,
Tags.Tips]),
Article(title:"The Best Baby Formulas of 2023", link:"https://www.verywellfamily.com/best-baby-formulas-4165193	",time: 15, tags: [Tags.Health,
Tags.Food,
Tags.Advice,
Tags.Tips]),
Article(title:"Choosing an Infant Formula", link:"https://www.cdc.gov/nutrition/infantandtoddlernutrition/formula-feeding/choosing-an-infant-formula.html",	time: 3, tags: [Tags.Health,
Tags.Food,
Tags.Advice,
Tags.Tips]),
Article(title:"Mumpower: These 5 Single Moms Battles Against Extreme Hardships And Emerged Victorious", link:"https://www.shethepeople.tv/top-stories/inspiration/inspiring-single-mothers-2/",	time: 5, tags: [Tags.Inspiring,
Tags.Experiences]),
Article(title:"5 Gutsy Women Share Their Stories Of Being A Single Mother In India", link:"https://www.womensweb.in/2018/07/five-women-share-their-stories-of-being-single-moms-in-india-july18wk4sr/	",time: 15, tags: [Tags.Inspiring,
Tags.Experiences]),
Article(title:"On Her Own: 3 Courageous Women Share What It Means to Be a Single Mother in India", link:"https://www.thebetterindia.com/174279/india-single-mother-inspiring-womens-day/	",time: 10, tags: [Tags.Inspiring,
Tags.Experiences,]),
];
